name: Tests
on: [push, pull_request]
jobs:
  test:
    name: Test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]
    env:
      TOOLS_DIRECTORY: tools
    steps:
      - name: Get the sources
        uses: actions/checkout@v1
      - name: Install Node 16
        uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Install the .NET 6 SDK
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '6.0.x'
      - name: Run a specific Cake script
        uses: ./
        with:
          script-path: build.cake
      