name: Tests
on: [push, pull_request]
jobs:
  test:
    name: Test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]
    env:
      TOOLS_DIRECTORY: tools
    steps:
      - name: Get the sources
        uses: actions/checkout@v1
      - name: Run a specific Cake script
        uses: ./
        with:
          script-path: build.cake
      